const express = require('express');
const router = express.Router();
const DailyTask = require('../models/DailyTask');
const CropCycle = require('../models/CropCycle');

// Helper function to set time to start of today (00:00:00)
const getTodayRange = () => {
  const start = new Date();
  start.setHours(0, 0, 0, 0);
  const end = new Date();
  end.setHours(23, 59, 59, 999);
  return { start, end };
};

// GET /api/daily-plan - Get or auto-generate today's plan
router.get('/', async (req, res) => {
  try {
    const userId = req.query.userId || 'demo-user';
    const { start, end } = getTodayRange();

    // 1. Check if tasks already exist for today
    let tasks = await DailyTask.find({
      userId,
      date: { $gte: start, $lte: end }
    });

    // 2. If no tasks exist, auto-generate default tasks based on active crops
    if (tasks.length === 0) {
      const activeCrops = await CropCycle.find({ userId, status: 'Active' });

      const autoGeneratedTasks = [
        {
          userId,
          date: new Date(),
          taskType: 'Irrigation',
          description: 'Check soil moisture and execute morning watering.',
          isCompleted: false
        },
        {
          userId,
          date: new Date(),
          taskType: 'Disease Check',
          description: 'Inspect leaf undersides for early spots or fungal signs.',
          isCompleted: false
        }
      ];

      // Add crop-specific task if active crops exist
      if (activeCrops.length > 0) {
        autoGeneratedTasks.push({
          userId,
          date: new Date(),
          taskType: 'General',
          description: `Inspect growth health for active crop: ${activeCrops[0].cropName}`,
          relatedCropId: activeCrops[0]._id,
          isCompleted: false
        });
      }

      tasks = await DailyTask.insertMany(autoGeneratedTasks);
    }

    res.json({ success: true, count: tasks.length, tasks });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

// PATCH /api/daily-plan/:id/toggle - Toggle task completion state
router.patch('/:id/toggle', async (req, res) => {
  try {
    const task = await DailyTask.findById(req.params.id);
    if (!task) {
      return res.status(404).json({ success: false, message: 'Task not found' });
    }

    task.isCompleted = !task.isCompleted;
    await task.save();

    res.json({ success: true, task });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

// POST /api/daily-plan - Manually add a custom task
router.post('/', async (req, res) => {
  try {
    const { userId, description, taskType, relatedCropId } = req.body;
    const newTask = new DailyTask({
      userId: userId || 'demo-user',
      date: new Date(),
      taskType: taskType || 'General',
      description,
      relatedCropId
    });

    await newTask.save();
    res.status(201).json({ success: true, task: newTask });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

module.exports = router;